# OBJECT ORIENTED PROGRAMMING

# COMMON TOPIC IN ALMOST ALL POPULAR PROGRAMMING LANGUAGES(PYTHON, JAVA, C++)
# WITH COMMON IDEA WITH DIFERENT SYNTAX

# OOP IS JUST A STYLEWAY TO WRIGHT CODE

# VERY HELPFUL IN REAL WORLD PROGRAMSS

# WE WILL SE OTHER ADVANTAGES WHEN WE WILL START LEARNING OOP

# class , object(instance), method

# list class
# list object
# method

l = [1,2,3,4,5,5,9]
l.append(7) #thnis append is method of class